const USER_ROLES = Object.freeze({
  VILLAGER: 'VILLAGER',
  COMMUNITY_LIAISON_OFFICER: 'COMMUNITY_LIAISON_OFFICER',
  FIELD_RANGER: 'FIELD_RANGER',
});

const LANGUAGES = Object.freeze({ EN: 'en', SI: 'si', TA: 'ta' });

const INCIDENT_TYPES = Object.freeze({
  ELEPHANT_NEAR_VILLAGE: 'ELEPHANT_NEAR_VILLAGE',
  CROP_DAMAGE: 'CROP_DAMAGE',
  PROPERTY_DAMAGE: 'PROPERTY_DAMAGE',
  PERSON_INJURED: 'PERSON_INJURED',
  SNARE_POACHING: 'SNARE_POACHING',
  OTHER_ANIMAL: 'OTHER_ANIMAL',
});

const INCIDENT_SOURCE = Object.freeze({ APP: 'APP', SMS: 'SMS' });

const INCIDENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  DUPLICATE: 'DUPLICATE',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

/** Statuses of a root report that still await an officer's decision. */
const UNDECIDED_STATUSES = Object.freeze([INCIDENT_STATUS.PENDING, INCIDENT_STATUS.UNDER_REVIEW]);

const URGENCY = Object.freeze({ NORMAL: 'NORMAL', URGENT: 'URGENT' });

const ELEPHANT_COUNT_BANDS = Object.freeze({ ONE: '1', TWO_TO_FIVE: '2_5', SIX_PLUS: '6_PLUS' });

const OCCURRED_WHEN = Object.freeze({ NOW: 'NOW', EARLIER_TODAY: 'EARLIER_TODAY' });

const VERIFICATION_DECISIONS = Object.freeze({ VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' });

const VERIFICATION_METHODS = Object.freeze({
  CALL_REPORTER: 'CALL_REPORTER',
  SITE_VISIT: 'SITE_VISIT',
  PHOTO_REVIEW: 'PHOTO_REVIEW',
  SENSOR_DATA: 'SENSOR_DATA',
});

const REJECTION_REASONS = Object.freeze({
  DUPLICATE_OR_RESOLVED: 'DUPLICATE_OR_RESOLVED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  INCORRECT_LOCATION: 'INCORRECT_LOCATION',
  OTHER: 'OTHER',
});

/** What a villager sees: Received -> Being checked -> Outcome. */
const REPORT_PROGRESS = Object.freeze({
  RECEIVED: 'RECEIVED',
  BEING_CHECKED: 'BEING_CHECKED',
  OUTCOME: 'OUTCOME',
});

const MAP_MARKER_STATES = Object.freeze({
  UNVERIFIED: 'UNVERIFIED',
  ACTION_NEEDED: 'ACTION_NEEDED',
  VERIFIED: 'VERIFIED',
});

const NOTIFICATION_TYPES = Object.freeze({
  URGENT_INCIDENT: 'URGENT_INCIDENT',
  INCIDENT_OUTCOME: 'INCIDENT_OUTCOME',
  FIELD_ACTION: 'FIELD_ACTION',
});

const SMS_DIRECTION = Object.freeze({ INBOUND: 'INBOUND', OUTBOUND: 'OUTBOUND' });

const SMS_LOG_STATUS = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED_FORMAT: 'REJECTED_FORMAT',
  FAILED: 'FAILED',
});

/** Duplicate detection rule from UC3.1 step 4: same type, within 1 km and 2 hours. */
const DUPLICATE_RULE = Object.freeze({ RADIUS_M: 1000, WINDOW_MINUTES: 120 });

const PHOTO_RULES = Object.freeze({
  MAX_BYTES: 5 * 1024 * 1024,
  ALLOWED_TYPES: Object.freeze({
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
  }),
  SIGNED_URL_TTL_SECONDS: 3600,
});

const LIMITS = Object.freeze({
  MAP_WINDOW_DAYS: 30,
  QUEUE_MAX_ROWS: 100,
  NEARBY_COLLAR_RADIUS_M: 2000,
  NEAREST_VILLAGE_MAX_M: 20000,
});

module.exports = {
  USER_ROLES,
  LANGUAGES,
  INCIDENT_TYPES,
  INCIDENT_SOURCE,
  INCIDENT_STATUS,
  UNDECIDED_STATUSES,
  URGENCY,
  ELEPHANT_COUNT_BANDS,
  OCCURRED_WHEN,
  VERIFICATION_DECISIONS,
  VERIFICATION_METHODS,
  REJECTION_REASONS,
  REPORT_PROGRESS,
  MAP_MARKER_STATES,
  NOTIFICATION_TYPES,
  SMS_DIRECTION,
  SMS_LOG_STATUS,
  DUPLICATE_RULE,
  PHOTO_RULES,
  LIMITS,
};
