const USER_ROLES = Object.freeze({
  VILLAGER: 'VILLAGER',
  COMMUNITY_LIAISON_OFFICER: 'COMMUNITY_LIAISON_OFFICER',
  FIELD_RANGER: 'FIELD_RANGER',
  PARK_MANAGER: 'PARK_MANAGER',
  OPERATIONS_OFFICER: 'OPERATIONS_OFFICER',
});

const LANGUAGES = Object.freeze({ EN: 'en', SI: 'si', TA: 'ta' });

const INCIDENT_TYPES = Object.freeze({
  ELEPHANT_NEAR_VILLAGE: 'ELEPHANT_NEAR_VILLAGE',
  CROP_DAMAGE: 'CROP_DAMAGE',
  PROPERTY_DAMAGE: 'PROPERTY_DAMAGE',
  PERSON_INJURED: 'PERSON_INJURED',
  SNARE_POACHING: 'SNARE_POACHING',
  OTHER_ANIMAL: 'OTHER_ANIMAL',
});

const INCIDENT_SOURCE = Object.freeze({ APP: 'APP', SMS: 'SMS' });

const INCIDENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  DUPLICATE: 'DUPLICATE',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

/** Statuses of a root report that still await an officer's decision. */
const UNDECIDED_STATUSES = Object.freeze([INCIDENT_STATUS.PENDING, INCIDENT_STATUS.UNDER_REVIEW]);

const URGENCY = Object.freeze({ NORMAL: 'NORMAL', URGENT: 'URGENT' });

const ELEPHANT_COUNT_BANDS = Object.freeze({ ONE: '1', TWO_TO_FIVE: '2_5', SIX_PLUS: '6_PLUS' });

const OCCURRED_WHEN = Object.freeze({ NOW: 'NOW', EARLIER_TODAY: 'EARLIER_TODAY' });

const VERIFICATION_DECISIONS = Object.freeze({ VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' });

const VERIFICATION_METHODS = Object.freeze({
  CALL_REPORTER: 'CALL_REPORTER',
  SITE_VISIT: 'SITE_VISIT',
  PHOTO_REVIEW: 'PHOTO_REVIEW',
  SENSOR_DATA: 'SENSOR_DATA',
});

const REJECTION_REASONS = Object.freeze({
  DUPLICATE_OR_RESOLVED: 'DUPLICATE_OR_RESOLVED',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  INCORRECT_LOCATION: 'INCORRECT_LOCATION',
  OTHER: 'OTHER',
});

/** What a villager sees: Received -> Being checked -> Outcome. */
const REPORT_PROGRESS = Object.freeze({
  RECEIVED: 'RECEIVED',
  BEING_CHECKED: 'BEING_CHECKED',
  OUTCOME: 'OUTCOME',
});

const MAP_MARKER_STATES = Object.freeze({
  UNVERIFIED: 'UNVERIFIED',
  ACTION_NEEDED: 'ACTION_NEEDED',
  VERIFIED: 'VERIFIED',
});

const NOTIFICATION_TYPES = Object.freeze({
  URGENT_INCIDENT: 'URGENT_INCIDENT',
  INCIDENT_OUTCOME: 'INCIDENT_OUTCOME',
  FIELD_ACTION: 'FIELD_ACTION',
});

const SMS_DIRECTION = Object.freeze({ INBOUND: 'INBOUND', OUTBOUND: 'OUTBOUND' });

const SMS_LOG_STATUS = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED_FORMAT: 'REJECTED_FORMAT',
  FAILED: 'FAILED',
});

/** Duplicate detection rule from UC3.1 step 4: same type, within 1 km and 2 hours. */
const DUPLICATE_RULE = Object.freeze({ RADIUS_M: 1000, WINDOW_MINUTES: 120 });

const PHOTO_RULES = Object.freeze({
  MAX_BYTES: 5 * 1024 * 1024,
  ALLOWED_TYPES: Object.freeze({
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/webp': 'webp',
  }),
  SIGNED_URL_TTL_SECONDS: 3600,
});

const LIMITS = Object.freeze({
  MAP_WINDOW_DAYS: 30,
  QUEUE_MAX_ROWS: 100,
  NEARBY_COLLAR_RADIUS_M: 2000,
  NEAREST_VILLAGE_MAX_M: 20000,
});

/** UC4 report types (ReportType enumeration). */
const REPORT_TYPES = Object.freeze({
  INCIDENT_SUMMARY: 'INCIDENT_SUMMARY',
  HOTSPOT_MAP: 'HOTSPOT_MAP',
  PATROL_COVERAGE: 'PATROL_COVERAGE',
  HUMAN_WILDLIFE_CONFLICT: 'HUMAN_WILDLIFE_CONFLICT',
});

/** UC1 – patrol sessions and the incidents a ranger logs in the field. */
const PATROL_STATUS = Object.freeze({ ACTIVE: 'ACTIVE', COMPLETED: 'COMPLETED' });

const PATROL_INCIDENT_TYPES = Object.freeze({
  SNARE_POACHING: 'SNARE_POACHING',
  CARCASS: 'CARCASS',
  ELEPHANT_SIGHTING: 'ELEPHANT_SIGHTING',
  ILLEGAL_ACTIVITY: 'ILLEGAL_ACTIVITY',
  OTHER_ANIMAL: 'OTHER_ANIMAL',
  OTHER: 'OTHER',
});

const PATROL_RULES = Object.freeze({ MAX_BATCH: 50, MAX_NOTE_LENGTH: 500 });

const EXPORT_FORMATS = Object.freeze({ PDF: 'PDF', CSV: 'CSV' });

/** Sections a manager can include in an exported report (UC4c, wireframe A2). */
const EXPORT_SECTIONS = Object.freeze({
  KPI_SUMMARY: 'KPI_SUMMARY',
  HOTSPOT_MAP: 'HOTSPOT_MAP',
  COVERAGE_GAPS: 'COVERAGE_GAPS',
  CONFLICT_TRENDS: 'CONFLICT_TRENDS',
  INCIDENT_LIST: 'INCIDENT_LIST',
});

/** UC4 rules from the revised scenario (section 7.4.5). */
const ANALYTICS_RULES = Object.freeze({
  MAX_RANGE_YEARS: 3,
  DEFAULT_BANDWIDTH_M: 500,
  UNPATROLLED_DAYS: 14,
  GRID_CELL_M: 250,
  TOP_HOTSPOTS: 5,
  CONFLICT_TYPES: Object.freeze([
    INCIDENT_TYPES.ELEPHANT_NEAR_VILLAGE,
    INCIDENT_TYPES.CROP_DAMAGE,
    INCIDENT_TYPES.PROPERTY_DAMAGE,
    INCIDENT_TYPES.PERSON_INJURED,
  ]),
});

/** UC2: Wildlife Collar Boundary Alerts (Hanaan / IT23594586) */
const ALERT_STATUS = Object.freeze({
  RAISED: 'RAISED',
  VILLAGE_SMS_SENT: 'VILLAGE_SMS_SENT',
  DISPATCHED: 'DISPATCHED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  ESCALATED: 'ESCALATED',
  RESOLVED: 'RESOLVED',
  FALSE_ALARM: 'FALSE_ALARM',
  DELAYED_INCIDENT: 'DELAYED_INCIDENT',
  ACTIVE: 'ACTIVE',
});

const BREACH_SEVERITY = Object.freeze({
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
});

const PROXIMITY_STATUS = Object.freeze({
  INSIDE: 'INSIDE',
  APPROACHING: 'APPROACHING',
  OUTSIDE: 'OUTSIDE',
});

const DISPATCH_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  TIMEOUT_ESCALATED: 'TIMEOUT_ESCALATED',
  REASSIGNED: 'REASSIGNED',
  RESOLVED: 'RESOLVED',
});

const CAMERA_REVIEW_STATUS = Object.freeze({
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED_ALERT: 'APPROVED_ALERT',
  DISMISSED: 'DISMISSED',
});

const RESPONSE_ACTION = Object.freeze({
  DISPATCH_RANGER: 'DISPATCH_RANGER',
  MONITOR_CLOSELY: 'MONITOR_CLOSELY',
  NOTIFY_COMMUNITY: 'NOTIFY_COMMUNITY',
  MARK_FALSE_ALARM: 'MARK_FALSE_ALARM',
});

const ZONE_TYPE = Object.freeze({
  FARMLAND: 'FARMLAND',
  VILLAGE: 'VILLAGE',
  ROAD: 'ROAD',
  RAILWAY: 'RAILWAY',
  BUFFER: 'BUFFER',
  CORE: 'CORE',
  SETTLEMENT_BOUNDARY: 'SETTLEMENT_BOUNDARY',
  CORRIDOR: 'CORRIDOR',
});

module.exports = {
  ALERT_STATUS,
  BREACH_SEVERITY,
  PROXIMITY_STATUS,
  DISPATCH_STATUS,
  CAMERA_REVIEW_STATUS,
  RESPONSE_ACTION,
  ZONE_TYPE,
  USER_ROLES,
  LANGUAGES,
  INCIDENT_TYPES,
  INCIDENT_SOURCE,
  INCIDENT_STATUS,
  UNDECIDED_STATUSES,
  URGENCY,
  ELEPHANT_COUNT_BANDS,
  OCCURRED_WHEN,
  VERIFICATION_DECISIONS,
  VERIFICATION_METHODS,
  REJECTION_REASONS,
  REPORT_PROGRESS,
  MAP_MARKER_STATES,
  NOTIFICATION_TYPES,
  SMS_DIRECTION,
  SMS_LOG_STATUS,
  DUPLICATE_RULE,
  PHOTO_RULES,
  LIMITS,
  REPORT_TYPES,
  PATROL_STATUS,
  PATROL_INCIDENT_TYPES,
  PATROL_RULES,
  EXPORT_FORMATS,
  EXPORT_SECTIONS,
  ANALYTICS_RULES,
};
